# Generated by Django 4.1.7 on 2023-04-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.IntegerField(max_length=7, null=True),
        ),
    ]
