# Generated by Django 4.1.7 on 2023-04-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_rename_customer_address_customer_address_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zip",
            field=models.IntegerField(null=True),
        ),
    ]
